---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
    service: ${FRONTEND_REPO}
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: |-
      export PATH=/opt/IBM/node-v4.2/bin:$PATH

      npm install
      npm install -g bower
      bower install
      npm install -g gulp-cli

      gulp node
- name: Deploy to Test
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: 'Test Job'
    type: tester
    script: |-
      #!/bin/bash
      # Add test scripts here
  - name: Deploy Test
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_TEST_APP_NAME}
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -f manifest-frontend.yml
- name: Deploy to Production
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  jobs:
  - name: Deploy Prod
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -f manifest-frontend.yml
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
