---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
    service: ${BACKEND_REPO}
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.12.7, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.2.2, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.2/bin:$PATH
      npm install
- name: Deploy To Test
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy Test
    type: deployer
    target:
      region_id: ${BE_PROD_REGION_ID}
      organization: ${BE_PROD_ORG_NAME}
      space: ${BE_PROD_SPACE_NAME}
      application: ${BE_CF_TEST_APP_NAME}
    script: |
      #!/bin/bash
      if [ ${SETUP} = "true" ] ; then
        # Create Services
        cf create-service conversation lite "${BE_CF_APP_NAME}"-conversation
        cf create-service cloudantNoSQLDB lite "${BE_CF_APP_NAME}"-cloudant
        cf create-service language_translator lite "${BE_CF_APP_NAME}"-language-translator
        cf create-service speech_to_text standard "${BE_CF_APP_NAME}"-stt
        cf create-service text_to_speech standard "${BE_CF_APP_NAME}"-tts
        cf create-service tone_analyzer lite "${BE_CF_APP_NAME}"-tone-analyzer
      fi

      cf push "${CF_APP}" -f manifest-backend.yml
      
      if [ ${SETUP} = "true" ] ; then
        # Bind Services
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-conversation
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-cloudant
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-language-translator
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-stt
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-tts
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-tone-analyzer
      fi

      # View logs
      cf logs "${CF_APP}" --recent
- name: Deploy to Production
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
    enabled: false
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${BE_PROD_REGION_ID}
      organization: ${BE_PROD_ORG_NAME}
      space: ${BE_PROD_SPACE_NAME}
      application: ${BE_CF_APP_NAME}
    script: |-
      #!/bin/bash
      cf push "${CF_APP}" -f manifest-backend.yml

      if [ ${SETUP} = "true" ] ; then
        # Bind Services
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-conversation
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-cloudant
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-language-translator
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-stt
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-tts
        cf bind-service "${CF_APP}" "${BE_CF_APP_NAME}"-tone-analyzer
      fi

      ${SETUP} = "false"

      # View logs
      cf logs "${CF_APP}" --recent
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
